### PR TITLE
remove sjb generated xml files that got obsoleted

### PR DESCRIPTION
**Pull request by ingvagabund**
Extend the openshif-ansible suite with install->upgrade of containerized and system containers deployment. I have already pushed the updated jobs and xml files.

The mentions jobs already merged and updated:
* https://github.com/openshift/aos-cd-jobs/pull/724 containerized
* https://github.com/openshift/aos-cd-jobs/pull/725 system containers

### CODE REVIEW

**Comment by ingvagabund** [comment]
@kargakis @stevekuznetsov PTAL

**Comment by stevekuznetsov** [comment]
We're triggering the jobs individually from Prow so I don't think we need this change. The larger suite jobs are not being used.

**Comment by ingvagabund** [comment]
I believe we need this so all the openshift-ansible related jobs are wrapped under the same category, i.e. `openshift-ansible`.

**Comment by stevekuznetsov** [comment]
Not sure I follow -- the multi-job that is based on that suite definition is no longer used for anything. We can merge this but realistically we should just delete it.

**Comment by ingvagabund** [comment]
If you check https://ci.openshift.redhat.com/jenkins/ and search for `OpenShift Ansible` category. It wraps all `test_pull_request_openshift_ansible` prefixed jobs (and others). If removal of the `openshift-ansible` test suite will not remove the category, I will prepare the PR removing both `test_pull_request_openshift_ansible` and `merge_pull_request_openshift_ansible` myself.

**Comment by stevekuznetsov** [comment]
yeah, the category is a simple regex grouping of jobs in there. feel free to make that PR

**Comment by ingvagabund** [comment]
@stevekuznetsov done, PTAL

**Comment by stevekuznetsov** [comment]
Can you also delete the XML generated from it, please?

**Comment by ingvagabund** [comment]
@stevekuznetsov done. I have also implemented a simple script that will detect generated xml files that has no underlying yml file.

**Comment by ingvagabund** [comment]
Not sure about `sjb/generated/test_pull_request_origin_aggregated_logging_prior.xml` but I could not find any yml file for it either. I found only:

```vi
./sjb/config/common/test_suites/origin_aggregated_logging.yml
./sjb/config/test_cases/test_branch_origin_aggregated_logging_prior.yml
./sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible_json_file.yml
./sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible.yml
./sjb/config/test_suites/merge_pull_request_origin_aggregated_logging.yml
./sjb/config/test_suites/test_pull_request_origin_aggregated_logging.yml
```

**Comment by ingvagabund** [comment]
The underlying job was removed by https://github.com/openshift/aos-cd-jobs/pull/523 but the generated xml file remained. So I believe we are free to remove the `sjb/generated/test_pull_request_origin_aggregated_logging_prior.xml` as well.

**Comment by stevekuznetsov** [comment]
Thanks, this looks really good.

**Pull request merged**
