### PR TITLE
Remove extended_conformance_install from testing origin PR

### PR DESCRIPTION
**Pull request by jhadvig**
@stevekuznetsov @smarterclayton PTAL
as you spoke I've removed extended_conformance_install from testing origins PR.

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

**Comment by jhadvig** [comment]
Will push the changes to jenskins after this got merge

**Comment by jhadvig** [comment]
@stevekuznetsov @smarterclayton I've updated the PR so it can be merged after we are ready to ditch the install job.

**Comment by stevekuznetsov** [comment]
If you think it's not enough work for a card, also change the upgrade job here to not do the first upgrade -- install the latest of previous release, then do one upgrade to current. That's all we are waiting on to get rid of install and re-introduce upgrade to the merge.

**Comment by stevekuznetsov** [comment]
We also want to update the `sjb/config/test_suites/test_branch_origin.yml`

**Comment by jhadvig** [comment]
@stevekuznetsov  commet addressed. I see that the install_upgrade job is running green so I guess we can merge this. Pls let me know will push the changes after merge

**Comment by stevekuznetsov** [comment]
Agreed, job looks green to me too. You can push changes.

**Comment by jhadvig** [comment]
Done

**Pull request merged**
