### PR TITLE
create separate jobs for integration and e2e

### PR DESCRIPTION
**Pull request by deads2k**
separate integration tests and e2e tests since the integration ones don't need images.

This creates net new jobs to practice with and ensure success before we change.

### CODE REVIEW

**Comment by kargakis** [comment]
Fixes https://github.com/openshift/aos-cd-jobs/issues/408

**Comment by deads2k** [comment]
> Fixes #408

Does it now. spiffy.  Care to review the matching pull here: https://github.com/openshift/origin/pull/15530 ?

**Comment by stevekuznetsov** [comment]
These LGTM

**Comment by stevekuznetsov** [comment]
@deads2k you need a pull to update prow and submitqueue configmaps too

**Comment by deads2k** [comment]
> @deads2k you need a pull to update prow and submitqueue configmaps too

ok, but I can get these separately, right?

**Comment by stevekuznetsov** [comment]
Not a huge fan of `just_integration` -- renaming it is going to be hairy if we want it to become `integration` later .... can we come up with something better?

**Comment by deads2k** [comment]
> Not a huge fan of just_integration -- renaming it is going to be hairy if we want it to become integration later .... can we come up with something better?

I figured this was easiest path.  
 1. Create two new jobs, don't modify old.  
 2. Test new jobs to make sure they work
 3. activate new jobs.
 4. Remove old job
 5. clone the just_integration job
 6. wait for the next time you're going to reset the list of jobs and switch back.

Keeps the queue operating at each step without a big bang, right?

**Comment by stevekuznetsov** [comment]
It's going to cause a thundering herd of triggers for the integration job when you clone it and add it back in but yeah it should not actually be an issue I don't think

**Pull request merged**
