### PR TITLE
DRY, elliottest=>elliott

### PR DESCRIPTION
**Pull request by sosiouxme**
DRY some repeat whitespace handling.
Looks like the path-less and user-less elliott works fine, let's make
that the norm.

### CODE REVIEW

**Comment by tbielawa** [comment]
I see this here, given the problems we're having with refresh images right now I am hesitant to make changes there. Or would this fix some of that? I thought I saw you comment that the buildlib.elliott command was busted there too?

**Comment by sosiouxme** [comment]
refresh-images invocation of elliott is already busted. this is to fix it.

**Comment by sosiouxme** [comment]
@tbielawa I did a bug sweep with it and it seems to work. Merge?

**Comment by sosiouxme** [comment]
The next step, of course, is to use `elliott find-builds --use-default-advisory rpm` in `refresh-errata` and do away with specifying the advisory at all.

**Pull request merged**
