### PR TITLE
[wip] Move jobs from branches to master.

### PR DESCRIPTION
**Pull request by bbguimaraes**
@jupierce: PTAL.

These are most likely not the only changes needed.

Generated by this script, if you want to do some testing (it creates a local
mirror of the official repo, so we can also test #134):

```sh
#!/bin/sh
set -eu

dir=${TMPDIR:-/tmp}/aos_cd_jobs
mkdir -p "$dir/"
rm -rf "$dir/origin.git/" "$dir/clone/"
git clone --quiet --mirror \
    "${LOCAL_MIRROR:-https://github.com/openshift/aos-cd-jobs.git}" \
    "$dir/origin.git/"
git clone --quiet "$dir/origin.git/" "$dir/clone/"
cd "$dir/clone/"
git config user.name test
git config user.email test@example.com
non_job_branches='build-scripts tower-scripts jjb sjb'
for x in $non_job_branches; do
    mkdir -p "$x"
    git archive "origin/$x" | tar -C "$x/" -x
done
git add .
git commit --quiet --message 'Move scripts from branches to master.'
git push --quiet --delete origin $non_job_branches
for x in $(git branch --list --remote --no-merged master); do
    mkdir -p "jobs/${x#origin/}"
    git archive "$x" | tar -C "jobs/${x#origin}" -x
done
git add .
git commit --quiet --message 'Move jobs from branches to master.'
git mv \
    jobs/disabled/build/scheduled/m-w-f/Jenkinsfile \
    jobs/disabled/build/scheduled/m-w-f/Jenkinsfile.disabled
git commit --quiet --message 'Disable the `build/scheduled/m-w-f` job.'
```

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
What other steps will be necessary after this?

**Comment by bbguimaraes** [comment]
@jupierce, @stevekuznetsov: updated to the latest master, not much changed. In
summary:

- branches `build-scripts`, `build/openshift-scripts`: (without the `build/`
  prefix), `tower-scripts` become directories in the root directory.
- branches `jjb`, `sjb`: don't have a `Jenkinsfile`, so no branches will be
  created.  The directories in `jobs/` are still there.  I'm not sure what to
  do here.
- branch `test_clayton_metrics_gather`: no idea what this is, but same as the
  previous item.
- branch `disabled/build/scheduled/m-w-f`: disabled on the last commit by
  renaming the `Jenkinsfile`.
- all the other branches: become directories under `jobs/`.

**Comment by stevekuznetsov** [comment]
- `jjb` and `sjb` should just become top-level subdirectories of the repo
 - `test_clayton_metrics_gather` I will delete

**Comment by bbguimaraes** [comment]
Updated.  The top-level directory of master is now:

```
├── build-scripts/
├── docs/
├── jjb/
├── jobs/
├── README.md
├── sjb/
└── tower-scripts/
```

And the branches/jobs that will result when the script is executed:

```
├── build/make-puddle
├── build/openshift-scripts
├── build/ose
├── build/ose-pipeline
├── build/ose-rebase-test
├── build/refresh-images
├── build/scheduled/ose
├── build/scheduled/t-th
├── build/stage-to-prod
├── cluster/dockertesting
├── cluster/operation
├── cluster/sprint-control
└── package-dockertested
```

**Pull request merged**
