### PR TITLE
lower thresholds for disk/memory install checks

### PR DESCRIPTION
**Pull request by sosiouxme**
This paves the way for https://github.com/openshift/openshift-ansible/pull/4161 to merge and not break everyone's installs.

### CODE REVIEW

**Comment by sosiouxme** [comment]
@stevekuznetsov when you get a chance... let me know if there's anything I need to do to get this in.

**Comment by stevekuznetsov** [comment]
If there are not going to be runtime-configured, please shove them into the `sjb/inventory/group_vars/OSEv3/general.yml` or if you expect there to be more make a new file `diagnostics.yml` in there.

**Comment by sosiouxme** [comment]
@stevekuznetsov thanks, much better approach. Done.

**Comment by stevekuznetsov** [comment]
LGTM

**Pull request merged**
