### PR TITLE
add origin to synced repos

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@kargakis @stevekuznetsov follow up to your comment: https://github.com/openshift/aos-cd-jobs/pull/1249/files#r175103664

ptal

**Comment by kargakis** [comment]
/lgtm

cc @bbguimaraes

**Comment by kargakis** [comment]
Changes pushed

**Comment by bparees** [comment]
thanks @kargakis

**Comment by bbguimaraes** [comment]
Thanks, @bparees.

**Pull request merged**
