### PR TITLE
Switch gssapi PR to origin_built_release base

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
not sure if this does what I want or not... was following the example of test_pull_request_origin_extended_builds.yml

**Comment by stevekuznetsov** [comment]
run `sjb/generate.sh`

**Comment by enj** [comment]
@stevekuznetsov is this good?

**Comment by stevekuznetsov** [comment]
Has it been tested?

**Comment by enj** [comment]
No idea how to test it with https://github.com/openshift/origin/pull/17737

**Comment by stevekuznetsov** [comment]
Follow the directions to push the job under a new name and either manually trigger the new job or use our [`manual-trigger`](https://github.com/kubernetes/test-infra/tree/master/experiment/manual-trigger) tool to do it.

**Pull request merged**
