### PR TITLE
standardize some initialization

### PR DESCRIPTION
**Pull request by sosiouxme**
Removed some cruft like the workspace init that should no longer be needed.
Moved a number of common elements into commonlib and used them from our main jobs.

### CODE REVIEW

**Comment by sosiouxme** [comment]
This stuff was just *bugging* me.
@tbielawa @adammhaile

**Comment by tbielawa** [comment]
/lgtm

also, yes, faaaaaaancy

**Comment by sosiouxme** [comment]
I updated 3 more jobs. 173 lines removed for great value...

**Pull request merged**
