### PR TITLE
Removing 4.0 refs

### PR DESCRIPTION
**Pull request by adammhaile**
@jupierce @sosiouxme @tbielawa PTAL

### CODE REVIEW

**Comment by sosiouxme** [comment]
Did I really not LGTM this?
/lgtm

**Comment by sosiouxme** [comment]
Honestly the more I think about it... hard to imagine a case for having 4.0 in Jenkins that can justify the potential for confusion. I'd like to change the ocp-build-data branch to a tag for historical purposes but preventing PRs against it. But in Jenkins... nah, kill it with fire.

**Comment by adammhaile** [comment]
Alright, fair. /unhold

**Pull request merged**
