### PR TITLE
Move PR artifacts under pr-logs/pulls in GCS

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @kargakis @smarterclayton any reason we didn't follow upstream convention here in the first place?

### CODE REVIEW

**Comment by kargakis** [comment]
> /cc @kargakis @smarterclayton any reason we didn't follow upstream convention here in the first place?

Not that I know of

lgtm

**Comment by smarterclayton** [comment]
Maybe the convention changed.  Can you also open PRs for openshift/origin-gce?

We might want to move all the old data too.

**Comment by stevekuznetsov** [comment]
> Can you also open PRs for openshift/origin-gce?

Not sure what you mean -- isn't the only GCS stuff in there for the cluster registry?

**Comment by stevekuznetsov** [comment]
> Also change zz_origin_gce

Uses `branch-logs` which doesn't exist upstream -- they just aggregate by job under `logs` for all jobs

**Comment by stevekuznetsov** [comment]
@smarterclayton any comments before I merge this

**Pull request merged**
