### PR TITLE
[ART-4866] promote-assembly: run build-microshift after promoting a release

### PR DESCRIPTION
**Pull request by vfreex**

### CODE REVIEW

**Comment by thegreyd** [comment]
Changes look good, maybe worth running a dry-run hack job to see if everything works as expected?
In the jira story I see retry mechanism and slack notification on build failure, curious if we are covering it here?

**Comment by vfreex** [comment]
> Changes look good, maybe worth running a dry-run hack job to see if everything works as expected? In the jira story I see retry mechanism and slack notification on build failure, curious if we are covering it here? Edit: I see that they are covered here https://github.com/openshift/aos-cd-jobs/pull/3286/files

@thegreyd , yes, there is a dry-run (with unrelated steps commented out) https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/yuxzhu/job/aos-cd-builds/job/build%252Fpromote-assembly/59/console

Retry is handled by Doozer. Doozer retries 3 times in case of rpm build failure.

**Comment by vfreex** [comment]
Another test run https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/yuxzhu/job/aos-cd-builds/job/build%252Fpromote-assembly/61/console after the second push.

**Pull request merged**
