### PR TITLE
add image-inspector images to be built and pushed

### PR DESCRIPTION
**Pull request by enoodle**
Jobs to build and push https://github.com/openshift/image-inspector

### CODE REVIEW

**Comment by enoodle** [comment]
@stevekuznetsov Please take a look

**Comment by stevekuznetsov** [comment]
@smarterclayton do we want this in the main push job for now?

**Comment by smarterclayton** [comment]
No

On Feb 6, 2018, at 5:15 PM, Steve Kuznetsov <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> do we want this in the
main push job for now?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/aos-cd-jobs/pull/1070#issuecomment-363622132>,
or mute the thread

**Comment by oourfali** [comment]
@smarterclayton we need to push a new image inspector image.
When we discussed that offline we were told to post this PR.

So, shall we abandon it and push the new image manually (that's what we did so far).

**Comment by stevekuznetsov** [comment]
OK, these LGTM.

**Comment by stevekuznetsov** [comment]
Jobs pushed up

**Pull request merged**
