### PR TITLE
use yum to find pkg verrel if tag doesn't work

### PR DESCRIPTION
**Pull request by richm**
use yum to find pkg verrel if tag doesn't work
This is a hack, but I don't know what else to do until the package
verrel for the 3.7 branch packages are a little more reasonable

### CODE REVIEW

**Comment by richm** [comment]
@stevekuznetsov @jcantrill logging CI for 3.7 branch is broken without this patch.  I've successfully tested with a cherrypick for 3.7

**Comment by stevekuznetsov** [comment]
Can you explain the issue a bit more here?

**Comment by richm** [comment]
We use this method to determine the correct rpm package verrel and image tag to use for branch releases: https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/test_pull_request_origin_aggregated_logging_ansible.yml#L67

specifically, this bit:
```
           # pkg ver is closest_tag with leading "-" instead of "v"
           pkgver=$( echo "${closest_tag}" | sed 's/^v/-/' )
```
e.g. for logging branch `release-3.7` it assumes there is a tag like `v3.7.0-rc.0`, which translates into an rpm package verrel like `-3.7.0-rc.0`.  Except this is not working for 3.7 pre-release(?) packages which have a verrel like this: `-3.7.0-0.rc.0.0.$commit_hash` where `$commit_hash` is the commit hash from origin that was used to produce the rpms.

Maybe this will all go away once 3.7 is officially released, but for now it takes this gross hack to figure out what the rpm verrel is.

**Comment by stevekuznetsov** [comment]
Hmm. SJB really sucks for this. Why do you need to resolve the closest tag? If we're on `release-3.6` you should be OK to use `v3.6` or `-3.6` for the version, won't that give you latest 3.6?

**Comment by richm** [comment]
> won't that give you latest 3.6?

Yes, works fine for 3.6, but fails for 3.7.

**Comment by stevekuznetsov** [comment]
D'oh. Ew ew ew ew. Sorry about this mess. Are you happy with these changes? I can merge now.

**Comment by richm** [comment]
I can't really say that I'm "happy" with these changes but this will have to do for now so we can have CI working for release-3.7.

**Comment by stevekuznetsov** [comment]
@richm Yep. Can you publish these or should I?

**Comment by richm** [comment]
@stevekuznetsov I will publish - thanks!

**Comment by richm** [comment]
pushed

**Pull request merged**
