### PR TITLE
catalog: change origin build and add logging

### PR DESCRIPTION
**Pull request by jpeeler**
Depends on https://github.com/openshift/origin/pull/18788 merging, will mark as non-WIP once that occurs. Edit: I forgot that PR didn't merge into the master branch - not a pre-requisite. 

This makes builds use HEAD for both origin and catalog such that out of
sync images won't ever occur. (See
https://github.com/openshift/origin/pull/18536#issuecomment-365084264.)

Add logging for catalog pods so that debugging is easier.

### CODE REVIEW

**Comment by jpeeler** [comment]
@eriknelson the changes (at least syntactically) here are minor. Been a while since I had looked at it to recall what it entailed.

**Comment by jpeeler** [comment]
@stevekuznetsov This is ready to merge now. The changes have been pushed to jenkins.

**Comment by jpeeler** [comment]
Repushed to jenkins.

**Comment by jpeeler** [comment]
@jupierce can you merge this?

**Comment by stevekuznetsov** [comment]
eeek, sorry, missed this -- can you regenerate your XML, re-push and e-mail me or ping me on IRC for this merge?

**Pull request merged**
