### PR TITLE
add allbuilds flag for elliott

### PR DESCRIPTION
**Pull request by Ximinhan**
at GA time we need to attach all builds to get CDN repo mapped correctly

### CODE REVIEW

**Comment by Ximinhan** [comment]
ref: https://github.com/openshift/elliott/pull/461

**Comment by thegreyd** [comment]
This looks good to me but if there's only one usecase of running at candidate/ga time, then we should code that up?

**Comment by Ximinhan** [comment]
@thegreyd  this will be needed during the RC period, also prevent manually do it for every release

**Review by vfreex — COMMENTED** [review]
Generally lgtm.

**Review by vfreex — APPROVED** [review]
/lgtm

**Pull request merged**
