### PR TITLE
Add rpm based CRIO CI job

### PR DESCRIPTION
**Pull request by sdodson**
Depends on https://github.com/openshift/openshift-ansible/pull/7425

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
How urgent is this? If not p0 can we try to use the new format?

**Comment by sdodson** [comment]
I'd want to have this job working by end of week.

**Comment by stevekuznetsov** [comment]
EOW gives us ages. Let's sync tomorrow about how we might be able to implement this job without 2k LOC copies

**Comment by smarterclayton** [comment]
Any update on this?  The current crio job is not correct and we can't test with it anymore.

**Comment by smarterclayton** [comment]
Specifically openshift/openshift-ansible#7486 can't test crio because the system container in 3.9 is busted (until we rebase we can't use the new crio image).

Also, we need to be careful to make sure we have specific cri-o install branches - 1.9 and 1.10 must be used appropriately for each branch (and we can't switch to 1.10 until we get the rebase landed).

**Comment by ashcrow** [comment]
:+1: on getting this finished.

Is the system container defective or is it a matter of version matching for Openshift? If the system container is broken please make sure an issue is opened so folks can fix it.

**Pull request merged**
