### PR TITLE
Node ports and the hostpath provisioner should be enabled

### PR DESCRIPTION
**Pull request by smarterclayton**
Otherwise these jobs can't test parts of the conformance suite

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Pushed up

**Comment by smarterclayton** [comment]
I think this broke install_update, it's complaining about syntax errors in the master-config.  I'm going to revert and repush.

**Comment by smarterclayton** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16379/test_pull_request_origin_extended_conformance_install_update/6270/

**Comment by smarterclayton** [comment]
Doing a quick test to confirm what the break is in the syntax

**Comment by smarterclayton** [comment]
What actually got written into the config:

```
  controllerArguments:
    '{"enable-hostpath-provisioner":'
```

**Comment by stevekuznetsov** [comment]
:\

**Comment by smarterclayton** [comment]
The space and single quote placement confused ansible and bash.  Fixed in https://github.com/openshift/aos-cd-jobs/pull/653

**Pull request merged**
