### PR TITLE
Switch Jenkins to use minimal profile

### PR DESCRIPTION
**Pull request by adambkaplan**
/assign @stevekuznetsov 

This is more of a formality. Jobs here have been updated on Jenkins

### CODE REVIEW

**Comment by gabemontero** [comment]
nope don't have authority :-)

**Comment by sosiouxme** [comment]
@adambkaplan @akram is this still relevant and correct? @stevekuznetsov or I have the merge button...

**Comment by adambkaplan** [comment]
@sosiouxme yes this is still correct. I had already pushed the new job defs to our Jenkins instance.

**Pull request merged**
