### PR TITLE
Revert "Revert "Merge pull request #313 from jhadvig/target_branch""

### PR DESCRIPTION
**Pull request by jhadvig**
Reverts openshift/aos-cd-jobs#335

### CODE REVIEW

**Comment by jhadvig** [comment]
@stevekuznetsov PTAL

**Comment by stevekuznetsov** [comment]
Let's run a clone job for the upgrade and just make sure that the final version of OpenShift installed is not that silly `3.6.0-0.0` one

**Comment by jhadvig** [comment]
Here is the cloned upgrade [job](https://ci.openshift.redhat.com/jenkins/view/All/job/jhadvig-test/7/consoleFull) .... if you search for "ORIGIN_UPGRADE_RELEASE_VERSION" you will see that prober version is being upgrade to

**Comment by stevekuznetsov** [comment]
FYI you can look at [`origin_package_history.log`](https://ci.openshift.redhat.com/jenkins/view/All/job/jhadvig-test/7/s3/download/generated/origin_package_history.log) to see history for `yum` for the `origin` package.

**Pull request merged**
