### PR TITLE
Modify browbeat pipeline script to load up all the params

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This commit modifies the browbeat script to load and pass all the
params defined in the property file so that we need not modify the
script when a new param is added.

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@jeremyeder @akrzos PTAL.

**Comment by mbruzek** [comment]
This change looks good to me. +1 

It will avoid us having to update the groovy code each time a property or parameter changes!

**Comment by akrzos** [comment]
Should this also modify the browbeat.properties file located in https://github.com/openshift/aos-cd-jobs/tree/master/alderaan/property_files 

The OpenStack specifically looks out of date as well.  I assume those are just example files and not used elsewhere.

Also does this specifically set the properties file name to "browbeat.properties"?  Such that we can not use other names?

**Comment by chaitanyaenr** [comment]
@akrzos the property files are just examples but we need to keep them updated like you said.
About the property file name, it can have a different name. We get the file and rename it to browbeat.properties before reading the params.

I have the updated the PR to address the comments. PTAL.

**Comment by akrzos** [comment]
@chaitanyaenr I see it now.  This looks good as the pipeline stands right now.  When we get a staging cluster back I have several more vars for OSP in order to reduce staging cluster build time and we will have OSP13 specific vars but we can fix that when we have the hardware available to test.

**Comment by chaitanyaenr** [comment]
@akrzos @mbruzek @jeremyeder is the PR ready for merge?

**Comment by akrzos** [comment]
LGTM, Thanks @chaitanyaenr

**Pull request merged**
