### PR TITLE
update build/refresh-images

### PR DESCRIPTION
**Pull request by sosiouxme**
Allow includes as well as excludes
Make RETRY retry just the builds that failed
Default to the team email
Other minor tweaks

### CODE REVIEW

**Comment by sosiouxme** [comment]
Since I can't figure out how to test this, it's probably broken.
@smunilla @adammhaile

**Comment by sosiouxme** [comment]
I tested this with a single image at https://buildvm.openshift.eng.bos.redhat.com:8443/job/Experimental/job/lmeyer/job/build%252Frefresh-images/2/console and it didn't explode!

**Comment by sosiouxme** [comment]
@smunilla @adammhaile PTAL

**Comment by sosiouxme** [comment]
@adammhaile how do we get this to merge then... green button? (I don't have it)

**Comment by adammhaile** [comment]
@sosiouxme - @tbielawa or @jupierce would need to hit the button

**Pull request merged**
