### PR TITLE
Record plashet state information in plashet directory

### PR DESCRIPTION
**Pull request by jupierce**
Write operations logs and plashet.yml (metadata about the operation) to the plashet directory. This will allow us to review what happened during assembly and also provide information to the consumers of the plashet.

### CODE REVIEW

**Comment by vfreex** [comment]
Seems a more robust way (to avoid race conditions) is call `koji_api.getLastEvent` first then use that event ID for every `getLatestBuilds` call in the same command invocation.

**Comment by jupierce** [comment]
I like it!

**Comment by jupierce** [comment]
@vfreex updated with the suggestion.

**Pull request merged**
