### PR TITLE
Enable approvers, disable silent logging

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Now that we are ready to enable the approvers for pull requests, a pull
request for a branch that we do not have an approver for will result in
an error and we will honor the result of the approver that we call.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

@jupierce this is the PR to enable the approvers, we can merge and push when we're ready

### CODE REVIEW

**Comment by jupierce** [comment]
Thanks, @stevekuznetsov . lgtm.

**Comment by stevekuznetsov** [comment]
@jupierce are we pushing this button sometime this week?

**Comment by jupierce** [comment]
@stevekuznetsov We should aim to enable devcut mode on 5/24.

**Comment by stevekuznetsov** [comment]
This will just turn on the approvers -- changing branch status is done with the Jenkins jobs

**Comment by kargakis** [comment]
Where are we getting the approvers from?

**Comment by stevekuznetsov** [comment]
@kargakis what do you mean?

**Comment by kargakis** [comment]
> Now that we are ready to enable the approvers for pull requests

I am assuming that this follows the upstream model of approvers but in any case I would expect "the list of approvers" to be an actual list of names that Rosie allows PRs with approval from to get merged.

**Comment by stevekuznetsov** [comment]
> I am assuming that this follows the upstream model of approvers

Sorry for the bad naming here, it has nothing to do with upstream approvers concept. I'll add to the README.

**Pull request merged**
