### PR TITLE
update-base-images: enable s390x builds

### PR DESCRIPTION
**Pull request by yselkowitz**
CC: @sosiouxme

### CODE REVIEW

**Comment by yselkowitz** [comment]
https://jira.coreos.com/browse/ART-871 is a prerequisite.

**Comment by sosiouxme** [comment]
LGTM but
/hold
until we have the repos in place

**Comment by yselkowitz** [comment]
@sosiouxme how are the repo files managed for these builds?

**Comment by sosiouxme** [comment]
@yselkowitz they're just in dist-git and we don't rewrite them

**Comment by sosiouxme** [comment]
/unhold
per http://pkgs.devel.redhat.com/cgit/containers/elasticsearch/commit/?h=rhaos-4.0-rhel-7&id=c6161df031f8461f1c227bd67f7a3ee0e602f9de

**Comment by yselkowitz** [comment]
@sosiouxme filed a patch for the repo files in https://jira.coreos.com/browse/ART-946

**Pull request merged**
