### PR TITLE
Run Oh the system container, Run!

### PR DESCRIPTION
**Pull request by ingvagabund**
Let's do it.

### CODE REVIEW

**Comment by ingvagabund** [comment]
@sdodson @giuseppe @ashcrow @stevekuznetsov @jhadvig

**Comment by ingvagabund** [comment]
@stevekuznetsov this needs to be run with OpenShift 3.6+. When the PR merges, will it affect 3.5 and less as well?

**Comment by stevekuznetsov** [comment]
Tests for all branches will run the full suite of tests, yes. How common are 3.5 backports?

**Comment by sdodson** [comment]
We won't be backporting system container support to 3.5.

**Comment by ingvagabund** [comment]
> How common are 3.5 backports?

From time to time there are some. Well, we can always check if all tests passed up to the system containers. However, the [test]/[merge] will always fail. So we would have to run [test] and then merge manually.

**Comment by stevekuznetsov** [comment]
@ingvagabund you can add a check to the job -- exit early with success:

```sh
if [[ "${OPENSHIFT_ANSIBLE_TARGET_BRANCH:-}" == "enterprise-3.5" ]]; then
    echo "[INFO] System containers are not supported, skipping."
    exit 0
fi
```

**Comment by stevekuznetsov** [comment]
@ingvagabund you'll need to test if we need that in one stage or in all stages.

**Comment by ingvagabund** [comment]
Not working currently, need to debug it before we merge it

**Comment by ingvagabund** [comment]
@stevekuznetsov feel free to merge it

**Pull request merged**
