### PR TITLE
Azure: resource group name too long

### PR DESCRIPTION
**Pull request by pschiffe**
Fix issue when resource group name is too long for Azure, remove repo and debug level when building the node image for publishing.

### CODE REVIEW

**Comment by pschiffe** [comment]
@kargakis

**Comment by kwoodson** [comment]
@pschiffe @kargakis,

```
>>> len('magentaciprtest747e412137')
25
>>> len('747e412137')
10
```

The proposed solution would work.  Do we want to just shorten the INSTANCE_PREFIX by a single character?

```
-e "openshift_azure_clusterid=magentaci${INSTANCE_PREFIX:0:9}"
```

Or shorten it on the way in? That probably makes the most sense.

**Comment by kargakis** [comment]
Any reason why we want the `magentaci` prefix in the first place?

**Comment by kwoodson** [comment]
The intention was to denote the CI process and be able to easily track/manage resource groups.

**Comment by pschiffe** [comment]
@kargakis @kwoodson just the `ci` prefix now.

**Comment by kargakis** [comment]
Please squash down to a single commit

**Comment by pschiffe** [comment]
@kargakis done

**Comment by kargakis** [comment]
Please don't forget to push the changes in Jenkins

**Comment by pschiffe** [comment]
Thanks, changes pushed.

**Pull request merged**
