### PR TITLE
tekton-pipelines: Refactoring artcd image Containerfile

### PR DESCRIPTION
**Pull request by vfreex**
- Rename Dockerfile to Containerfile.
- Decrease image size by using multi-stage build and cleaning up unused packages.
- Bump base image.
- Use non-root user.

Requires https://github.com/openshift/elliott/pull/279 and https://github.com/openshift/doozer/pull/580

### CODE REVIEW

**Review by joepvd — APPROVED** [review]
/lgtm

Think the word `dev` on the file system has another specific meaning, so would have chosen another user name. But let's just go with it :)

**Comment by vfreex** [comment]
Thanks.
Hold until PSI is back so I can test it before merging.
/hold

**Comment by vfreex** [comment]
Tested with https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/art-cd/tekton.dev~v1beta1~PipelineRun/gen-assembly-run-5rmzs/logs and https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/art-cd/tekton.dev~v1beta1~PipelineRun/prepare-release-y7tvsb/logs.

**Pull request merged**
