### PR TITLE
Downgrade to ansible 2.3 on release-3.7, release-3.6

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Have you tested this?

**Comment by sdodson** [comment]
@stevekuznetsov Yes, I'd pushed an updated  logging job and used it for this test run https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/6742/test_pull_request_openshift_ansible_logging/4853/?log#log

I'm not sure if test jobs have been updated since I pushed that one but it doesn't look as if the downgrade is being triggered on master. I can re-push and we can look for that condition if you'd like. I have an extremely hard time getting a pure test job constructed in a meaningful manner.

**Comment by stevekuznetsov** [comment]
Just wanted to see that we had all the required RPMs. I'll merge this and push it out.

**Comment by sdodson** [comment]
ack, thanks

**Pull request merged**
