### PR TITLE
print the s2i version

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero @stevekuznetsov ptal

**Comment by stevekuznetsov** [comment]
You can also look at `clone-log.txt` for versions of code cloned.

**Comment by stevekuznetsov** [comment]
Like this: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_jenkins/539/test_pull_request_jenkins_images/201/clone-log.txt

**Comment by bparees** [comment]
@stevekuznetsov thanks. did you update jenkins? I didn't want to stomp on anything you were doing so i didn't.

**Pull request merged**
