### PR TITLE
enable audit logging during CI runs

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/openshift/origin/issues/15041

### CODE REVIEW

**Comment by deads2k** [comment]
@stevekuznetsov @sdodson ptal

**Comment by sdodson** [comment]
i think this will work but I haven't personally tested this format.

**Comment by deads2k** [comment]
How do I run a test to make sure?

**Comment by stevekuznetsov** [comment]
Since this is in the repo and not in the job configuration testing it is a lot more involved -- you'd want to copy a test job and edit it so that it checks out this PR for the aos-cd-jobs repo. I've made the changes in my [`skuznets/deads-test`](https://github.com/stevekuznetsov/aos-cd-jobs/tree/skuznets/deads-test) tree and pushed the job up to Jenkins. Test job is running here: https://ci.openshift.redhat.com/jenkins/job/skuznets/3/console

**Comment by kargakis** [comment]
@stevekuznetsov needs to be documented

**Comment by deads2k** [comment]
> Since this is in the repo and not in the job configuration testing it is a lot more involved

Why wouldn't config be stored in the job configuration?

**Comment by stevekuznetsov** [comment]
> @stevekuznetsov needs to be documented

@kargakis sure, will do

> Why wouldn't config be stored in the job configuration?

@deads2k the files in the inventory are used from a checkout of this repository, they're not literally in the XML used to configure  job in Jenkins. In the future we hope to a) run Pod-based test jobs that bake in specific versions of infra dependencies and b) have versioned Groovy libraries for Jenkins pipeline job configuration.

**Comment by stevekuznetsov** [comment]
@kargakis documentation PR: https://github.com/openshift/aos-cd-jobs/pull/406

**Comment by stevekuznetsov** [comment]
@deads2k can you look at [the job artifacts](https://ci.openshift.redhat.com/jenkins/job/skuznets/3/s3/) and confirm audit logging worked as you expected?

**Comment by kargakis** [comment]
Seems like it's working
```
Jul 07 12:25:01 ip-172-18-15-132.ec2.internal origin-master[18142]: I0707 12:24:59.797295   18142 audit.go:125] 2017-07-07T12:24:59.797259138-04:00 AUDIT: id="b7df8ee4-409a-4afc-b7e8-9485e5d93226" ip="172.18.15.132" method="GET" user="system:openshift-master" as="<self>" asgroups="<lookup>" namespace="<none>" uri="/apis/extensions/v1beta1/thirdpartyresources"
Jul 07 12:25:01 ip-172-18-15-132.ec2.internal origin-master[18142]: I0707 12:24:59.797884   18142 audit.go:45] 2017-07-07T12:24:59.797867489-04:00 AUDIT: id="b7df8ee4-409a-4afc-b7e8-9485e5d93226" response="403"
Jul 07 12:25:01 ip-172-18-15-132.ec2.internal origin-master[18142]: I0707 12:24:59.797920   18142 panics.go:76] GET /apis/extensions/v1beta1/thirdpartyresources: (939.882µs) 403 [[openshift/v1.5.2+43a9be4 (linux/amd64) kubernetes/43a9be4] 172.18.15.132:34078]
Jul 07 12:25:01 ip-172-18-15-132.ec2.internal origin-master[18142]: W0707 12:24:59.798293   18142 storage_extensions.go:137] third party resource sync failed: User "system:openshift-master" cannot list all extensions.thirdpartyresources in the cluster
Jul 07 12:25:01 ip-172-18-15-132.ec2.internal origin-master[18142]: I0707 12:24:59.804469   18142 clusterquotamapping.go:306] Waiting for the caches to sync before starting the quota mapping controller workers
Jul 07 12:25:01 ip-172-18-15-132.ec2.internal origin-master[18142]: I0707 12:24:59.839695   18142 audit.go:125] 2017-07-07T12:24:59.839653646-04:00 AUDIT: id="779f0717-9e61-4671-b444-2166adcac123" ip="172.18.15.132" method="GET" user="system:openshift-master" as="<self>" asgroups="<lookup>" namespace="default" uri="/api/v1/namespaces/default/services/kubernetes"
```

**Comment by stevekuznetsov** [comment]
Thanks @deads2k @kargakis

**Pull request merged**
