### PR TITLE
Remove PR-specific checks from base AMI

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by kargakis** [comment]
https://ci.openshift.redhat.com/jenkins/view/AMIs/job/ami_build_origin_int_rhel_base/524

**Comment by stevekuznetsov** [comment]
AMI is only valid for master so this seems reasonable

**Comment by kargakis** [comment]
Sorry for not mentioning it but previously the job was broken because `PULL_BASE_REF` does not exist in its env. Trying to get it to pass tests now.

**Pull request merged**
