### PR TITLE
Build Origin releases inside of the hack/env container

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
running here: https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended/

**Comment by jhadvig** [comment]
Looks like the running container is missing docker or socket ..hmmm

**Comment by stevekuznetsov** [comment]
Yeah, I forgot that `make release` is special and calls out to `hack/env` itself ... @smarterclayton do we want to unravel that?

**Comment by stevekuznetsov** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended/2

**Comment by stevekuznetsov** [comment]
@kargakis FYI failure at https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended/2/consoleFull#177669287658b6e51eb7608a5981914356 is what I saw in the PR you have as well -- the dotfile for release commit doesn't get copied back from hack/env and this causes subsequent steps to fail

**Comment by kargakis** [comment]
@stevekuznetsov which PR are you talking about? I don't remember this failure...

**Comment by stevekuznetsov** [comment]
@kargakis this is in the images installing from RPM PR

**Comment by smarterclayton** [comment]
We can only unravel it if every job depending on it changes.

**Comment by stevekuznetsov** [comment]
Alternatively we can migrate jobs to do an RPM release (won't call `hack/env`) and fill in `make release` in the future

**Comment by stevekuznetsov** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended/3/

**Comment by stevekuznetsov** [comment]
@smarterclayton it's not the worst thing in the world but this _is_ pretty ugly... we should get `hack/env make release` to work.

```
        make clean
        export OS_BUILD_IMAGE_ARGS=''
        hack/env hack/build-base-images.sh
        OS_ONLY_BUILD_PLATFORMS="linux/amd64" hack/build-release.sh
        OS_BUILD_ENV_EXCLUDE='_output/local/pkgdir' hack/env hack/build-images.sh
        OS_BUILD_ENV_EXCLUDE='_output/local/pkgdir' OS_BUILD_ENV_PRESERVE='_output/local/bin' hack/env hack/extract-release.sh
```

**Comment by kargakis** [comment]
In https://github.com/openshift/origin/pull/13642 I am switching `make release` to use `build-rpm-release` in favor of `build-release` since release binaries are built as part of rpmbuild. I am testing `hack/env make release` now.

**Comment by stevekuznetsov** [comment]
Awesome.

**Pull request closed without merging**
