### PR TITLE
[ART-1231] adding sign-artifacts to support multiarch

### PR DESCRIPTION
**Pull request by shiywang**
I have a question for how to test this PR which I left as a comment in https://jira.coreos.com/browse/ART-1231

### CODE REVIEW

**Comment by tbielawa** [comment]
I think it would be pertinent to include the architecture in the message we send over the bus to the robosig. This PR gets of the essential stuff set up correctly, I can include the change I just mentioned in my upcoming signing jobs PR.

**Comment by tbielawa** [comment]
> I think it would be pertinent to include the architecture in the message we send over the bus to the robosig. This PR gets of the essential stuff set up correctly, I can include the change I just mentioned in my upcoming signing jobs PR.

Unless our `release name` fields will explicitly include things like the arch? `4.2.0-s390x` ?

**Comment by sosiouxme** [comment]
Our release names should include the arch, yeah. I'm a little concerned someone will forget. In any case, they'll need to be distinguished somehow in Cincinnati, and that's how we planned to do it.

**Pull request merged**
