### PR TITLE
Adding initial sops

### PR DESCRIPTION
**Pull request by jupierce**
@mwoodson @tdawson 
The starting point for some simple standard operating procedures. Please let me know your thoughts. 

@tdawson Planning to fully automate the stage cut at some point with a Jenkins job, but until then, I wanted something we can reference. I also have "stage-sprint###" for the backup of each stage branch even though we discussed stage-<last ocp version> . The rationale being that it is easier and allows us to correlate  origin/stage-sprint130  and origin/stage-sprint130

### CODE REVIEW

**Comment by tdawson** [comment]
Are we missing openshift-ansible on these, or will that be done by the other group?

**Comment by stevekuznetsov** [comment]
Do we want to try to write out the SOP as shell?

```sh
sprint=123
for repo in origin origin-web-console ose openshift-ansible online; do
    git "clone git@github.com:openshift/${repo}.git"
    pushd "${repo}"
    git checkout stage
    git checkout -b "stage-${sprint}"
    git reset --hard master
    for ref in master stage "stage-${sprint}"; do
        git push --force origin "${ref}"
    done
    popd
done
```

**Comment by jupierce** [comment]
@stevekuznetsov If there is truly nothing else to it, then yes, we should just write a Jenkins job. This is mean to find and document any lingering details before we do so (e.g. Scott seemed interested when you talked about stage being a tracking branch for release-X.Y).

**Comment by jupierce** [comment]
@tdawson Thanks for catching that. I've added openshift-ansible.

**Pull request merged**
