### PR TITLE
[ART-2869] Start 4.9 pre-releases

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by sosiouxme** [comment]
LGTM but we still publish dev previews up until RC and there may be some use for them. Also we haven't started regular 4.9 build automation yet. So I'd say we should hold this until at or near 4.9 branch cut.

/hold

**Comment by sosiouxme** [comment]
/hold cancel
merge when there's someone around to watch things :)

**Comment by thiagoalessio** [comment]
merging today and watching it 👀

**Pull request merged**
