### PR TITLE
Fixup checkout directory for CRI-O

### PR DESCRIPTION
**Pull request by mrunalp**
Missed this earlier.
@runcom @stevekuznetsov @smarterclayton ptal.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by smarterclayton** [comment]
I’m not at a computer to push this but lgtm

**Comment by runcom** [comment]
LGTM

**Comment by runcom** [comment]
@kargakis PTAL for merge as well

**Comment by runcom** [comment]
BTW, these must be fixed as well https://github.com/openshift/aos-cd-jobs/blob/master/sjb/config/test_cases/ami_build_origin_int_rhel_crio.yml#L31-L32 @mrunalp

**Comment by mrunalp** [comment]
@runcom Fixed.

**Pull request merged**
