### PR TITLE
jenkins centos images are now built as docker.io/openshift/jenkins-*

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
/hold
@bparees I believe this would also need to be merged if https://github.com/openshift/jenkins/pull/444 is merged?

**Comment by bparees** [comment]
@jim-minter yeah i'd assume so.  this is going to take a little coordination.  Do you have permission to actually push the job changes to jenkins?

**Comment by bparees** [comment]
i've gone ahead and pushed this change to the job (i'm going to merge the other pr).

**Comment by bparees** [comment]
first build that picked up https://github.com/openshift/jenkins/pull/444 and these job changes is here:
https://ci.openshift.redhat.com/jenkins/job/push_jenkins_images/96/

please make sure it did what you wanted/expected.

**Comment by jim-minter** [comment]
thanks @bparees, results looked good to me.

**Pull request merged**
