### PR TITLE
Update catalog to sync repos using sync

### PR DESCRIPTION
**Pull request by jpeeler**
I've tested this using a test branch job (https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_service_catalog_test/), but copied the parameters from another job and am unsure how pull requests will change there.

(This supercedes https://github.com/openshift/aos-cd-jobs/pull/1513)

### CODE REVIEW

**Comment by jpeeler** [comment]
If the parent origin job handles merging PRs for origin, then I think this is good.

**Comment by jpeeler** [comment]
@stevekuznetsov This has already been pushed. Things appear to be working and my tests to ensure the repos are being synced worked too, but I have no idea how the code is automagically synced at this point.

**Comment by stevekuznetsov** [comment]
The log for the `clonerefs` tool should be uploaded, or if you grep for that tool name in the job log you will see the steps.

**Comment by stevekuznetsov** [comment]
This is the tool: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/clonerefs/README.md

**Pull request merged**
