### PR TITLE
Running against openshift-ansible master for es5.x aggregated logging…

### PR DESCRIPTION
**Pull request by ewolinetz**
… branch with correct flags

### CODE REVIEW

**Comment by ewolinetz** [comment]
@richm @stevekuznetsov PTAL

**Comment by ewolinetz** [comment]
This should address CI not working for https://github.com/openshift/origin-aggregated-logging/pull/892

**Comment by stevekuznetsov** [comment]
Changes are semantically reasonable but @richm should sign off

**Comment by stevekuznetsov** [comment]
Pushed up

**Pull request merged**
