### PR TITLE
[ART-3429] Configure upgrade edges in releases.yml

### PR DESCRIPTION
**Pull request by vfreex**
Requires https://github.com/openshift/doozer/pull/536

### CODE REVIEW

**Review by joepvd — APPROVED** [review]
/lgtm
/hold Wait for doozer pr

**Comment by vfreex** [comment]
/hold cancel
Doozer PR was merged.

**Comment by joepvd** [comment]
/lgtm

Welcome back, @vfreex 🎉

**Comment by vfreex** [comment]
@joepvd Thank you.

**Pull request merged**
