### PR TITLE
add 4.0 choice to jenkins version job

### PR DESCRIPTION
**Pull request by gabemontero**
so we can change the jenkins version in our 4.0 image 

@bparees @adammhaile ptal

### CODE REVIEW

**Comment by bparees** [comment]
lgtm, i dunno what it takes to get this merged/updated.

**Comment by gabemontero** [comment]
My mock builds do not seem to have updated  https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex

Perhaps I don't have requisite permission for that?

@tbielawa @adammhaile could one of you all try running a mock build to update the drop down for the aforementioned job?  Of is there another task that needs to be done?

**Comment by tbielawa** [comment]
I think you should be set now.

**Comment by gabemontero** [comment]
Yep I see it now.  Thanks @tbielawa

**Pull request merged**
