### PR TITLE
Prepare for transitioning images to do RPM installs

### PR DESCRIPTION
**Pull request by kargakis**
@stevekuznetsov ptal, this should help us transition to RPM installs in the images.

### CODE REVIEW

**Comment by kargakis** [comment]
> Running a test job of the build ami here: https://ci.openshift.redhat.com/jenkins/view/All/job/michalis_test/1/console

Switched to the base ami because the change there is more invasive (dropping make relase in favor of build-rpms).

**Comment by stevekuznetsov** [comment]
Looks good. Will we be able to get `hack/env make release` after your PR merges?

**Comment by kargakis** [comment]
> Looks good. Will we be able to get hack/env make release after your PR merges?

Yes, I'll retest it today but last time I did it, `make release` working fine with hack/env (plus the additional envs).

**Comment by kargakis** [comment]
> Yes, I'll retest it today but last time I did, make release was working fine with hack/env (plus the additional envs).

Works fine

**Comment by stevekuznetsov** [comment]
@kargakis ping when tests are happy

**Comment by kargakis** [comment]
@stevekuznetsov got a green build of the base ami in https://ci.openshift.redhat.com/jenkins/job/michalis_test/6/console

**Comment by stevekuznetsov** [comment]
It built base images before RPMs -- isn't that going to break your PR?

**Comment by kargakis** [comment]
> It built base images before RPMs -- isn't that going to break your PR?

No, I have removed the dependency to RPMs from the base image builds, see https://github.com/openshift/origin/pull/13642/files#diff-0d0b900bdcdb42ce4d30c02d3f3c6538R11 (https://github.com/openshift/origin/pull/13642#discussion_r113719062)

**Pull request closed without merging**
