### PR TITLE
Disable SELinux for upstream kubernetes CI temporarly

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

Though, we need to update the selinux package (whatever package it is).

### CODE REVIEW

**Comment by rhatdan** [comment]
What errors are you seeing?  AVC Messages?

**Comment by ingvagabund** [comment]
```
# ausearch -m avc
<no matches>
```

```
# grep AVC /var/log/audit/audit.log 
type=USER_AVC msg=audit(1528290513.755:2941): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  received policyload notice (seqno=2)  exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
type=USER_AVC msg=audit(1528290714.064:3621): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  received policyload notice (seqno=3)  exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
type=USER_AVC msg=audit(1528290714.065:3622): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  received policyload notice (seqno=4)  exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
```

Unfortunately, I see nothing

**Comment by ingvagabund** [comment]
Maybe?
```
Jun 21 14:16:35 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:16:40 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:26:55 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:26:56 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:26:57 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:26:58 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:26:58 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:50:40 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:50:40 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:50:41 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:50:42 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 21 14:50:42 ip-172-18-7-140 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
```

**Comment by ingvagabund** [comment]
Thanks, it helped:

```sh
type=AVC msg=audit(1529668102.726:2218): avc:  denied  { getattr } for  pid=29042 comm="sh" path="/var/log/containers/logger-pod_e2e-tests-kubelet-container-log-path-vf8kw_logger-container-039b15ca86967a424077ef004592a1716460cd2fe3bba82b4bae014e5e723046.log" dev="xvda2" ino=80086116 scontext=system_u:system_r:container_t:s0:c588,c768 tcontext=system_u:object_r:container_var_lib_t:s0 tclass=file

type=AVC msg=audit(1529668060.657:2151): avc:  denied  { net_admin } for  pid=30619 comm="systemd-tmpfile" capability=12  scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:system_r:systemd_tmpfiles_t:s0 tclass=capability
```

**Comment by rhatdan** [comment]
This looks like you are leaking the container logs into the container?

/var/log/containers/logger-pod_e2e-tests-kubelet-container-log-path-vf8kw_logger-container-039b15ca86967a424077ef004592a1716460cd2fe3bba82b4bae014e5e723046.log"

Is this intentional?  Do you want a confined container that can read the container logs?

**Comment by ingvagabund** [comment]
I did not check the test thoroughly yet. It's part of the kubernetes node e2e conformance test suite.

**Comment by ingvagabund** [comment]
> This looks like you are leaking the container logs into the container?
> Is this intentional? Do you want a confined container that can read the container logs?

In case of the containerized Kubelet, the container running the Kubelet needs to access logs of other containers. Is there a way to specify such a rule that only the Kubelet container (e.g. container with `hyperkube` name) will be able to access the logs?

**Comment by rhatdan** [comment]
I can create a new type container_logreader_t, which I could add the ability to read logs and then you would have to specify that type: container_logreader_t, to run your container with.

**Comment by rhatdan** [comment]
You might be able to build this yourself to see if it works.
```
# cat /tmp/mycontainer.te 
policy_module(mycontainer, 1.0)

# Container Logreader
container_domain_template(container_logreader)
logging_read_all_logs(container_logreader_t)
logging_read_audit_log(container_logreader_t)
```
Compile and install the policy module
```
make -f /usr/share/selinux/devel/Makefile
semodule -i mycontainer.pp
```
Now you can run the container with the container_logreader_t type.

```
# podman run -v /var/log:/var/log fedora cat /var/log/dan.log
cat: /var/log/dan.log: Permission denied
# podman run -v /var/log:/var/log --security-opt label=type:container_logreader_t fedora cat 
/var/log/dan.log
2018-01-22T12:51:50.869685453-05:00 stdout F hello
```

**Pull request closed without merging**
