### PR TITLE
Always continue image refresh jobs

### PR DESCRIPTION
**Pull request by smunilla**
There is almost never a circumstance when you want to abort or retry
an image refresh job. In 99% of cases you just want to push and attach
whatever you have.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
FYI This repo doesn't have auto-merges

**Comment by sosiouxme** [comment]
Can I suggest as an alternative https://github.com/openshift/aos-cd-jobs/pull/1690

**Comment by smunilla** [comment]
@sosiouxme #1690 seems to leave the RETRY/CONTINUE/ABORT option still up to the user. Am I reading that wrong or did we change our mind about the value of that?

**Comment by smunilla** [comment]
Discussed with @sosiouxme and I'm going to close this one.

**Comment by sosiouxme** [comment]
@smunilla sorry i completely failed to see your comment!

**Pull request closed without merging**
