### PR TITLE
ART-2000: fix the custom job to also build an el8 plashet

### PR DESCRIPTION
**Pull request by vfreex**
When the ocp4 job builds composes, it builds plashets for el7 and el8.
The custom job uses a different section of code in buildlib and only builds el7.

Consolidated the code into buildlib and fixed the custom job to also build el8.

Test job runs:
- https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/hack/job/yuxzhu/job/aos-cd-jobs/job/build%252Fcustom/4/console
- https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/hack/job/yuxzhu/job/aos-cd-jobs/job/build%252Focp4/3/

### CODE REVIEW

**Comment by jupierce** [comment]
@vfreex looks like a great start. Though it doesn't look like the ocp4 test run succeeded. I'm also concerned that the current implementation would break ocp4's build.stageMirrorRpms .

**Comment by sosiouxme** [comment]
ocp4 failed because it calls out to a job that's missing, before it gets to the plashet. so, inconclusive.

**Comment by vfreex** [comment]
@jupierce nice catch! `stageMirrorRpms` uses `rpmMirror.localPlashetPath` and `rpmMirror.plashetDirName` so I should keep them.

I also found the the following issues with stageMirrorRpms.  Should we fix them (in a separate effort)?
- ocp4 job only mirrors el7 plashet. el8 plashet is never mirrored.
- custom job doesn't mirror anything.
- stageMirrorRpms firstly rsyncs the plashet to a shared staging dir before copies to the final destination, but seems it is not protected by a lock.

**Comment by vfreex** [comment]
Running ocp4 hack build https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/hack/job/yuxzhu/job/aos-cd-jobs/job/build%252Focp4/4/console

**Comment by vfreex** [comment]
Seems the hack job passed the plashet creation and rpm mirroring stages. @jupierce @sosiouxme PTAL.

**Comment by jupierce** [comment]
@vfreex - we can open a separate card / PR if desired, but I'd just as soon fix the issues you mention with this work.
- We have not historically mirrored the .el8 plashet, but we should start doing so with 4.6 transitioning to RHEL8 base for everything.
- I'm hoping the custom job will go away soon for 4.x. If no one has complained yet, I'd say we don't worry about mirroring. 
- `firstly rsyncs the plashet to a shared staging dir before copies to the final destination, but seems it is not protected by a lock` . That is a subtle point -- and I hate relying on subtlety :) . It would cost us nothing to put a release specific lock around this so that it can't bite us in the future as we refine jobs.

**Comment by vfreex** [comment]
@jupierce Yeah, custom job doesn't seem required after we always build signed. But let's keep it until we officially deprecate it.

I added a new commit to this PR to wrap the mirroring RPMs stage with a lock.

**Comment by sosiouxme** [comment]
I think the custom job will always have a role, but greatly diminished (not a part of standard release work).

**Pull request merged**
