### PR TITLE
add extended_templates cron-based test

### PR DESCRIPTION
**Pull request by jim-minter**
@stevekuznetsov

### CODE REVIEW

**Comment by bparees** [comment]
i've kinda wanted a templates extended test job for a while now anyway, so +1

**Comment by stevekuznetsov** [comment]
LGTM

**Comment by stevekuznetsov** [comment]
Job is [live](https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_templates/) and first build running.

**Comment by jim-minter** [comment]
Thanks.

**Pull request merged**
