### PR TITLE
crio: drop managed ns test

### PR DESCRIPTION
**Pull request by giuseppe**
they were never added to openshift/release and the managed ns is the
default now so no need for a dedicated test.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM

On Friday, February 14, 2020, Giuseppe Scrivano <notifications@github.com>
wrote:
> /cc @haircommander
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/Xodg7ZoTn1GgRSAXOUBBX0D5XB33i5dKTYJsMU7itssBdq2QJT0ZN6YIGW_GKWNKXy5Vfh04OrSN3DXOsXSP5FcuEfBpAWCV69gCws-mMESbwlvtGQkd2UFKL1hsPgE0N2Alot68yhqDV2-VMEW0nXrxz4f-qAYSZu4jP9D-6uBQ4GeCJBZ3Eqo9DxVI04Hc04gqXbnN-mjTF9UlUeid2wdyrrFVsk-OG_wOdfgxHA=s0-d-e1-ft#https://github.com/notifications/beacon/ACFJQJZLLH7JYSMRJM2EK6LRC2EJLA5CNFSM4KVHBDO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELY3MCI.gif>

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@giuseppe needs a rebase.

**Comment by giuseppe** [comment]
rebased

**Pull request merged**
