### PR TITLE
Add openshift ansible crio pr test

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
@stevekuznetsov is this necessary or can we just add the prow config to call the existing crio job?
CC: @runcom @ashcrow

**Comment by stevekuznetsov** [comment]
No, we need this or we won't be syncing an O-A PR

**Comment by sdodson** [comment]
So LGT @stevekuznetsov  ?

**Comment by stevekuznetsov** [comment]
Sure -- you will need to add the config to run it, too -- it should not be blocking today (the origin version is at like <10% success rate ATM)

**Pull request merged**
