### PR TITLE
use oauth-proxy 1.1.0 for es and kibana

### PR DESCRIPTION
**Pull request by richm**
use oauth-proxy 1.1.0 for es and kibana

### CODE REVIEW

**Comment by richm** [comment]
ping - please comment or merge

**Comment by jcantrill** [comment]
@smarterclayton @simo5 was there any resolution how we could properly fix in ansible?  In the interim can we please merge to resolve short term

**Comment by simo5** [comment]
@jcantrill I di not understand what the issue was
/lgtm

**Comment by richm** [comment]
I rebased on top of latest and pushed again to jenkins to unblock logging CI

can we get this merged?

**Comment by stevekuznetsov** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
The real fix is to start promoting and using the same tagging scheme as everyone else in both ansbile and how you build and publish your images.  I think we're just going to torpedo the "teams get to use random tags and branch names" because it has never worked in practice the moment anyone else needs to interoperate with the team for CI.  oauth-proxy in origin and in OCP needs to follow the release tag pattern and use the same automation as everyone else to do so (ci-operator jobs, which I can help with).  Since we have to rebuild the images anyway in OCP CVEs and other rebuilds I don't see any benefit in having the ad-hoc versioning managed outside of a central CI pattern.

Since this is confined to the Jenkins jobs which have an end date, it's fine to do this for now.

**Comment by smarterclayton** [comment]
@simo5 should be pretty straightforward, will take a look at the repo and give you advice

**Comment by richm** [comment]
Because this PR has not merged, and no other solution is forthcoming, logging CI will be intermittently broken - e.g. https://github.com/openshift/origin-aggregated-logging/pull/1446
```
FAILURE after 59.978s: test/cluster/functionality.sh:70: executing 'oc get pod logging-kibana-2-8d47j -o jsonpath='{ .status.containerStatuses[?(@.name=="kibana-proxy")].ready }'' expecting any result and text 'true'; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
false
... repeated 60 times
Standard error from the command:
Error from server (NotFound): pods "logging-kibana-2-8d47j" not found
```
What do we need to do to solve this problem so that I don't have to constantly do `sjb/push-update-automatic.sh`?

**Comment by stevekuznetsov** [comment]
@smarterclayton please resolvce

**Pull request closed without merging**
