### PR TITLE
ART-238 | Always continue on AMI fail

### PR DESCRIPTION
**Pull request by adammhaile**
@tbielawa @jupierce

### CODE REVIEW

**Comment by jupierce** [comment]
lgtm. @adammhaile Can you make sure mwoodson@redhat.com, brawilli@redhat.com are also directly emailed?

**Comment by tbielawa** [comment]
Will do the needful after those emails are added

**Comment by adammhaile** [comment]
@tbielawa already done

**Comment by tbielawa** [comment]
@adammhaile where? I dont' see `brawilli` or `mwoodson` on the diff view of this PR.

**Comment by adammhaile** [comment]
@Justin Pierce <jupierce@redhat.com> instead of adding mwoodson@redhat.com,
brawilli@redhat.com  directly do you have a mailing list I should include?

**Comment by adammhaile** [comment]
per slack @jupierce, changed to openshift-cr@redhat.com

**Comment by adammhaile** [comment]
@tbielawa <tbielawa@redhat.com> Ahh, further discussion happened on
slack. @jupierce wanted me to add a mailing list instead. Which I did.

**Pull request merged**
