### PR TITLE
remove jenkins rhel image generation; defer to upcoming brew/prow

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees ptal

also, do we need a *_311 version of the files in question?  Or nuke the *_310 versions

I did confirm we are the only guys using rhel_base_images .... no other refs to that string in any of the yml files in this repo

### CODE REVIEW

**Comment by bparees** [comment]
> also, do we need a *_311 version of the files in question? Or nuke the *_310 versions

The job is smart enough to figure out the image tag to use based on information in the repo, right? So i think kill the 3.10 job?  (but we need to make sure the remaining jobs are running against all the release branches)

**Comment by gabemontero** [comment]
On Wed, Oct 10, 2018 at 12:01 PM Ben Parees <notifications@github.com>
wrote:

> also, do we need a *_311 version of the files in question? Or nuke the
> *_310 versions
>
> The job is smart enough to figure out the image tag to use based on
> information in the repo, right? So i think kill the 3.10 job? (but we need
> to make sure the remaining jobs are running against all the release
> branches)
>
and how we make sure the remaining jobs are run against all releases .... I
tried going through
https://ci.openshift.redhat.com/jenkins/view/All/job/test_branch_jenkins_images/configure
and
https://ci.openshift.redhat.com/jenkins/view/All/job/test_branch_jenkins_images_310/configure
but could not find anything branch related.

However, I think openshift/release prow presubmit stuff controls that
also.  In comparing them, it looks like the master presubmit has the
trigger for test_pull_request_jenkins_images, but not the 3.10 nor 3.11.

So yeah, I think we have to update those once this merges.

**Comment by gabemontero** [comment]
pushed remove of 3.10 files

**Comment by bparees** [comment]
lgtm, if we have to add stuff back in we will, but let's start by getting back to a working state.

**Comment by bparees** [comment]
@gabemontero i'll leave it up to you to run the push jobs script.

**Pull request merged**
