### PR TITLE
CRI-O: split critest from e2e

### PR DESCRIPTION
**Pull request by runcom**
@mrunalp @stevekuznetsov PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
related CRI-O PR https://github.com/kubernetes-incubator/cri-o/pull/1221

**Comment by runcom** [comment]
I guess I'll enable this in openshift/release once this is merged :)

**Comment by stevekuznetsov** [comment]
SGTM

**Comment by runcom** [comment]
We can pull this in once the cri-o PR is in

**Comment by mrunalp** [comment]
cri-o PR is merged.

**Comment by runcom** [comment]
:tada: I'm creating an openshift/release PR meanwhile

**Comment by runcom** [comment]
ok, PR created in openshift/release#497

**Comment by stevekuznetsov** [comment]
Generate XML

**Comment by runcom** [comment]
> Generate XML

Done, pushed generated xml for #947 as well

**Pull request merged**
