### PR TITLE
azure playbooks: use sync correctly

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@kargakis ptal and merge

**Comment by stevekuznetsov** [comment]
If you open a PR for your release repo fork you can use a `pull/111/head ` reference in the sync step for `openshift/release` and do less directory jumping

**Comment by kargakis** [comment]
Here is the PR (https://github.com/openshift/release/pull/799), assuming it gets merged today we can use release master.

**Comment by kargakis** [comment]
Other than @stevekuznetsov's comment, lgtm

**Comment by kargakis** [comment]
@pschiffe fyi

**Pull request merged**
