### PR TITLE
Copy the buildvm snapshot to an s3 bucket so we can send fewer email …

### PR DESCRIPTION
**Pull request by tbielawa**
…in the future.

### CODE REVIEW

**Comment by tbielawa** [comment]
> Great! Part of this PR should be:
> 
> * a documentation change of where to find these snapshots
> * verification that the team can access the bucket
> * possibly a checkbox in the onboarding doc

Good idea. I'll write up some docs.

**Comment by tbielawa** [comment]
> Great! Part of this PR should be:
> 
> * a documentation change of where to find these snapshots
> * verification that the team can access the bucket
> * possibly a checkbox in the onboarding doc

I wrote up the docs. Some of what you mentioned isn't required. Please take a look https://mojo.redhat.com/docs/DOC-1206910#jive_content_id_BuildVM_Snapshot_Logs

**Comment by joepvd** [comment]
Nice! This depends on `buildvm`, though, and I'd be most interested in the contents if `buildvm` is not available.

**Comment by joepvd** [comment]
Thanks for docs improvement. :shipit:

**Pull request merged**
