### PR TITLE
Set CPU and Memory accounting in the base AMI

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @derekwaynecarr FYI
/cc @sdodson PTAL

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Removed conditional on the `daemon-reexec` ... works AFAICT:

```console
$ cat <<EOF >origin-ami-accounting.conf
> [Manager]
> DefaultCPUAccounting=yes
> DefaultMemoryAccounting=yes
> EOF
$ mkdir -p /etc/systemd/system.conf.d/
$ mv origin-ami-accounting.conf /etc/systemd/system.conf.d/
$ systemctl daemon-reexec
$ systemctl show docker.service --property CPUAccounting --property MemoryAccounting
CPUAccounting=yes
MemoryAccounting=yes
```

**Comment by sdodson** [comment]
Yeah, if you're doing this in the base image build and you're sure that the host will be rebooted you don't need any of the systemctl daemon-reexec stuff

**Comment by stevekuznetsov** [comment]
> you don't need any of the systemctl daemon-reexec stuff

We run tests on the AMI after we mint it but without a reboot AFAICT(???) so I'll keep it in, can't hurt.

**Comment by stevekuznetsov** [comment]
https://ci.openshift.redhat.com/jenkins/job/ami_build_origin_int_rhel_base/52/ running with these changes

**Pull request merged**
