### PR TITLE
Run image-registry integration tests

### PR DESCRIPTION
**Pull request by legionus**
@kargakis please review

### CODE REVIEW

**Comment by kargakis** [comment]
@legionus can you also run `sjb/generate.sh`?

**Comment by legionus** [comment]
@kargakis done

**Comment by legionus** [comment]
@kargakis something is wrong. After this change, the tests do not start, although I was sure that they are already working.

https://github.com/openshift/image-registry/pull/17
https://github.com/openshift/image-registry/pull/18

**Comment by kargakis** [comment]
@legionus I don't see any problem.

https://github.com/openshift/image-registry/pull/17 lacks a lgtm label
https://github.com/openshift/image-registry/pull/18 has the extended test in flight

**Comment by kargakis** [comment]
Jenkins wasn't updated for some reason. Fixed.

**Pull request merged**
